#!/bin/sh

case "$1" in
  start)
	echo "Starting kexecboot..."
	kexecboot
	;;
  stop)
	killall kexecboot
        ;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
